# Official Uganda Revenue Authority (URA) Design System Tokens
URA_BLUE = "#1B3A75"
URA_BLUE_DARK = "#122A57"
URA_BLUE_LIGHT = "#3B82F6"
URA_BLUE_PALE = "#EFF6FF"
URA_YELLOW = "#FFF200"
URA_YELLOW_DARK = "#E6D700"
URA_DARK = "#30302F"
URA_TEXT_MUTED = "#64748B"
URA_BG = "#F8FAFC"
URA_SURFACE = "#FFFFFF"
URA_GREEN = "#008751"

PALETTE = [URA_BLUE, URA_YELLOW, URA_BLUE_LIGHT, URA_GREEN, URA_DARK]

CATEGORY_COLOR_MAP = {
    "VAT": URA_BLUE,
    "EXCISE": URA_YELLOW,
    "LOCAL_SERVICE": URA_BLUE_LIGHT,
    "WITHHOLDING": URA_GREEN,
}

SESSION_TIMEOUT_SECONDS = 1800

